---
- name: ensure glance database is present
  mysql_db:
    login_host: "{{ glance_mysql_host }}"
    login_port: "{{ glance_mysql_port }}"
    login_user: root
    login_password: "{{ glance_mysql_root_password }}"
    name: glance
  register: create_glance_db

- name: ensure glance database user is present
  mysql_user:
    login_host: "{{ glance_mysql_host }}"
    login_port: "{{ glance_mysql_port }}"
    login_user: root
    login_password: "{{ glance_mysql_root_password }}"
    name: glance
    host: "{{ item }}"
    password: "{{ glance_mysql_glance_password }}"
    priv: glance.*:ALL
  with_items:
    - localhost
    - "%"

- name: create glance user in keystone
  keystone_user:
    endpoint: "{{ glance_identity_admin_url }}"
    token: "{{ glance_identity_admin_token }}"
    tenant: service
    user: glance
    password: "{{ glance_identity_glance_password }}"
- include: docker.yml
  when: glance_dockerized_deployment

- include: install.yml
  when: not glance_dockerized_deployment 

- include: offline_configuration.yml
  when: not glance_dockerized_deployment 

- name: wait until glance service is ready
  wait_for:
    delay: 1
    host: "{{ glance_image_endpoint_host }}"
    port: 9292
    state: started

- name: add glance user to the service tenant with the admin role
  keystone_user:
    endpoint: "{{ glance_identity_admin_url }}"
    token: "{{ glance_identity_admin_token }}"
    tenant: service
    user: glance
    role: admin

- name: add glance endpoint
  keystone_service:
    endpoint: "{{ glance_identity_admin_url }}"
    token: "{{ glance_identity_admin_token }}"
    region: "{{ glance_identity_region }}"
    name: glance
    type: image
    description: "Image Service"
    public_url: "{{ glance_image_public_url }}"
    internal_url: "{{ glance_image_internal_url }}"
    admin_url: "{{ glance_image_admin_url }}"


